/*
 * File: app/model/CustomerModel.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Arch105.model.CustomerModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.proxy.Rest',
        'Ext.data.field.Field'
    ],

    idProperty: 'CUST_NO',

    proxy: {
        type: 'rest',
        idParam: 'CUST_NO',
        url: 'http://localhost:8080/customer/'
    },

    fields: [
        {
            name: 'CUST_NO'
        },
        {
            name: 'CUSTOMER'
        },
        {
            name: 'CONTACT_FIRST'
        },
        {
            name: 'CONTACT_LAST'
        },
        {
            name: 'PHONE_NO'
        },
        {
            name: 'ADDRESS_LINE1'
        },
        {
            name: 'ADDRESS_LINE2'
        },
        {
            name: 'CITY'
        },
        {
            name: 'STATE_PROVINCE'
        },
        {
            name: 'COUNTRY'
        },
        {
            name: 'POSTAL_CODE'
        },
        {
            name: 'ON_HOLD'
        }
    ]
});