/*
 * File: app/model/Employee.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Arch104.model.Employee', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.Date'
    ],


    fields: [
        {
            name: 'employeeNo'
        },
        {
            name: 'rating'
        },
        {
            calculate: function(data) {
                var average, i,
                    ratings = data.rating || [],
                    count = ratings.length;

                for (i = 0, average = 0; i < count; i++) {
                    average += data.rating[i];
                }
                return average / ratings.length;
            },
            name: 'averageRating'
        },
        {
            type: 'int',
            name: 'salary',
            summary: 'sum'
        },
        {
            name: 'forename'
        },
        {
            name: 'surname'
        },
        {
            calculate: function(data) {
                return data.forename + ' ' + data.surname;
            },
            name: 'fullName'
        },
        {
            name: 'email'
        },
        {
            name: 'department'
        },
        {
            type: 'date',
            name: 'dob',
            dateFormat: 'Ymd'
        },
        {
            type: 'date',
            name: 'joinDate',
            dateFormat: 'Ymd'
        },
        {
            name: 'noticePeriod'
        },
        {
            type: 'int',
            name: 'sickDays',
            summary: 'average'
        },
        {
            type: 'int',
            name: 'holidayDays',
            summary: 'average'
        },
        {
            type: 'int',
            name: 'holidayAllowance',
            summary: 'average'
        },
        {
            name: 'avatar'
        },
        {
            type: 'int',
            name: 'ratingLastYear'
        },
        {
            type: 'int',
            name: 'ratingThisYear'
        }
    ]

});