/*
 * File: app/view/BigDataGridViewModel.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Arch104.view.BigDataGridViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.bigdatagrid',

    requires: [
        'Ext.app.bind.Formula'
    ],

    formulas: {
        ratingGroup: function(get) {
            var age = get('record.averageRating');

            if (age < 4) {
                return 0;
            }
            if (age < 5) {
                return 1;
            }
            if (age < 6) {
                return 2;
            }

            return 3;
        }
    }

});