/*
 * File: app/view/BigDataGrid.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Arch104.view.BigDataGrid', {
    extend: 'Ext.grid.Grid',
    alias: 'widget.bigdatagrid',

    requires: [
        'Arch104.view.BigDataGridViewModel',
        'Ext.grid.column.RowNumberer',
        'Ext.grid.column.Check',
        'Ext.grid.plugin.Editable',
        'Ext.grid.column.Date',
        'Ext.grid.plugin.ViewOptions',
        'Ext.grid.plugin.Summary',
        'Ext.grid.plugin.ColumnResizing',
        'Ext.grid.plugin.RowExpander',
        'Ext.grid.plugin.RowOperations'
    ],

    viewModel: {
        type: 'bigdatagrid'
    },
    height: '100%',
    shadow: true,
    width: '100%',
    store: 'DataGridStore',
    itemConfig: {
        body: {
            tpl: '<img src="{avatar}" height="100px" style="float:left;margin:0 10px 5px 0"><b>{name}<br></b>{dob:date}'
        }
    },
    grouped: true,
    title: 'Big Data Grid',

    columns: [
        {
            xtype: 'rownumberer'
        },
        {
            xtype: 'numbercolumn',
            minWidth: 100,
            dataIndex: 'employeeNo',
            text: 'Id'
        },
        {
            xtype: 'gridcolumn',
            width: 120,
            dataIndex: 'surname',
            text: 'Name'
        },
        {
            xtype: 'checkcolumn',
            width: 100,
            dataIndex: 'verified',
            text: 'Verified'
        },
        {
            xtype: 'datecolumn',
            width: 120,
            dataIndex: 'dob',
            text: 'Date of Birth',
            format: 'd-m-Y'
        },
        {
            xtype: 'gridcolumn',
            width: 100,
            align: 'center',
            cell: {
                xtype: 'widgetcell',
                widget: {
                    xtype: 'button',
                    text: 'Verify',
                    ui: 'action',
                    width: 80,
                    bind: {
                        tooltip: 'Verify {record.fullName}'
                    },
                    handler: function(btn){
                                var cell = btn.up(),
                                    rec = cell.getRecord();
                    
                                rec.set('verified', true);
                                Ext.Msg.alert('Verify', 'Verify ' + rec.get('forename') + ' ' + rec.get('surname'));
                            }
                }
            },
            text: 'Verify'
        },
        {
            xtype: 'datecolumn',
            width: 120,
            dataIndex: 'joinDate',
            editable: true,
            text: 'Join Date',
            format: 'd-m-Y'
        },
        {
            xtype: 'gridcolumn',
            text: 'Absences',
            columns: [
                {
                    xtype: 'gridcolumn',
                    width: 80,
                    align: 'center',
                    dataIndex: 'sickDays',
                    text: 'Illness'
                },
                {
                    xtype: 'gridcolumn',
                    width: 80,
                    align: 'center',
                    dataIndex: 'holidayDays',
                    text: 'Holidays'
                },
                {
                    xtype: 'gridcolumn',
                    width: 80,
                    align: 'center',
                    dataIndex: 'holidayAllowance',
                    formatter: 'number("0.00")',
                    summaryFormatter: 'number("0.00")',
                    text: 'Holiday Allowance'
                }
            ]
        },
        {
            xtype: 'gridcolumn',
            width: 100,
            dataIndex: 'noticePeriod',
            text: 'Notice Period'
        },
        {
            xtype: 'gridcolumn',
            width: 200,
            dataIndex: 'email',
            editable: true,
            editor: {
                xtpye: 'emailfield'
            },
            text: 'Email'
        },
        {
            xtype: 'gridcolumn',
            text: 'Ratings',
            columns: [
                {
                    xtype: 'numbercolumn',
                    width: 75,
                    dataIndex: 'averageRating',
                    text: 'Avg'
                },
                {
                    xtype: 'gridcolumn',
                    width: 80,
                    cell: {
                        xtype: 'widgetcell',
                        forceWidth: true,
                        widget: {
                            xtype: 'sparklineline'
                        }
                    },
                    dataIndex: 'rating',
                    text: 'All'
                }
            ]
        },
        {
            xtype: 'gridcolumn',
            summaryRenderer: function(value) {
                return Ext.util.Format.usMoney(value);
            },
            width: 120,
            align: 'right',
            dataIndex: 'salary',
            editable: true,
            formatter: 'usMoney',
            summary: 'average',
            text: 'Salary'
        }
    ],
    plugins: [
        {
            type: 'grideditable'
        },
        {
            type: 'gridviewoptions'
        },
        {
            type: 'gridsummaryrow'
        },
        {
            type: 'gridcolumnresizing'
        },
        {
            type: 'rowexpander'
        },
        {
            type: 'rowoperations'
        }
    ]

});